core/urls.py
from django.urls import path
from .views import HomeView, item_detail_view, CheckoutView, add_to_cart, remove_from_cart, OrderSummaryView, remove_single_from_cart, PaymentView, AddCouponView, RequestRefundView, ProfileView


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('product/<slug>/', item_detail_view, name="product"),
    path('add-coupon/', AddCouponView.as_view(), name="add-coupon"),
    path('add-to-cart/<slug>/', add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name="order-summary"),
    path('remove-single-item-from-cart/<slug>/',
         remove_single_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_options>', PaymentView.as_view(), name="payment"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('request-refund/', RequestRefundView.as_view(), name="request-refund")
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    """It represents an item on the website."""
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=15)
    label = models.CharField(choices=LABEL_CHOICES, max_length=15)
    slug = models.SlugField()
    description = models.TextField(default="No description provided")
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={"slug": self.slug})

    def get_saved_amount(self):
        return self.price - self.discount_price


class OrderItem(models.Model):
    """Just to creates a link between an order going on and actual items on the website."""
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_price(self):
        return (self.item.price * self.quantity)

    def get_total_discount_price(self):
        return (self.item.discount_price * self.quantity)

    def get_saved_amount(self):
        return self.get_total_price() - self.get_total_discount_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()


class Address(models.Model):
    """A model representing billing address related information for a model."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username}\'s {self.apartment_address}'

    class Meta:
        verbose_name_plural = "Addresses"


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    """An Order that can be placed on the website"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    is_ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        Address, related_name="billing_address", on_delete=models.SET_NULL, null=True, blank=True)
    shipping_address = models.ForeignKey(
        Address, related_name="shipping_address", on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey(Payment,
                                on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    recieved = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    """
        1. Item added to the cart
        2. Adding a billing address
        (Failed Checkout)
        3. Payment
        preprocessing, processing, packaging, etc..
        4. Being delivered
        5. Recieved
        6. Refunds
    """

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    def get_coupon_discount(self):
        if self.coupon:
            return ((self.get_total()) * (self.coupon.percentage)) / 100
        else:
            return 0

    def get_total_after_coupon(self):
        return self.get_total() - self.get_coupon_discount()


class Coupon(models.Model):
    """A model handling referral codes and coupons for an order."""
    code = models.CharField(max_length=15)
    percentage = models.FloatField(default=0)

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return f'{self.pk}'

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class CheckoutForm(forms.Form):
    # Handled requirement in the view
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo Code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': 4
        }
    ))
    email = forms.EmailField(required=True)

templates/bottom-scripts.html
{% load static %}
<!-- SCRIPTS -->
<!-- JQuery -->
<script
  type="text/javascript"
  src="{% static 'js/jquery-3.4.1.min.js' %}"
></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script
  type="text/javascript"
  src="{% static 'js/bootstrap.min.js' %}"
></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/iziToast.min.js' %}"></script>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}
checkout
{% endblock head_title %}
{% block content %}
<div class="grey lighten-3" style="margin: 0px; padding: 0px">
  <!-- Navbar -->
  <div class="col-12">{% include 'navbar.html' %}</div>
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">
      <!-- Heading -->
      <h2 class="my-5 h1 text-center"><u>Checkout form</u></h2>

      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-md-8 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card content-->
            <form class="card-body" method="POST" action="{% url 'checkout' %}" id="checkout-form">
              <h3>Shipping Address</h3>
              {% csrf_token %}
              <!--address-->
              <div class="hideable-shipping-form">
                <div class="md-form mb-5">
                  <input
                    type="text"
                    name="shipping_address"
                    id="id_shipping_address"
                    class="form-control"
                    placeholder="1234 Main St"
                  />
                  <label for="id_shipping_address" class=""
                    >Address<span class="asteriskField">*</span></label
                  >
                </div>

                <!--address-2-->
                <div class="md-form mb-5">
                  <input
                    type="text"
                    name="shipping_address2"
                    id="id_shipping_address"
                    class="form-control"
                    placeholder="Apartment or suite"
                  />
                  <label for="id_shipping_address" class=""
                    >Address 2 (optional)</label
                  >
                </div>

                <!--Grid row-->
                <div class="row">
                  <!--Grid column-->
                  <div class="col-lg-6 col-md-6 mb-4">
                    <label for="shipping_country" class="">
                      Shipping Country
                    </label>
                    {{form.shipping_country}}
                  </div>
                  <!--Grid column-->
                  <!--Grid column-->
                  <div class="col-lg-6 col-md-6 mb-4">
                    <label for="id_shipping_zip"
                      >Zip code<span class="asteriskField">*</span></label
                    >
                    <input
                      type="text"
                      name="shipping_zip"
                      class="form-control"
                      id="id_shipping_zip"
                      placeholder=""
                    />
                    <div class="invalid-feedback">Zip code required.</div>
                  </div>
                  <!--Grid column-->
                </div>
                <!--Grid row-->

                <hr />

                <div class="custom-control custom-checkbox">
                  <input
                    type="checkbox"
                    name="same_billing_address"
                    class="custom-control-input"
                    id="id_same_billing_address"
                  />
                  <label
                    class="custom-control-label"
                    for="id_same_billing_address"
                    >Billing address is same as my shipping address</label
                  >
                </div>
                <div class="custom-control custom-checkbox">
                  <input
                    type="checkbox"
                    name="set_default_shipping"
                    class="custom-control-input"
                    id="id_set_default_shipping"
                  />
                  <label
                    class="custom-control-label"
                    for="id_set_default_shipping"
                    >Save this shipping address for future</label
                  >
                </div>
              </div>
              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input
                  type="checkbox"
                  name="use_default_shipping"
                  class="custom-control-input"
                  id="id_use_default_shipping"
                />
                <label
                  class="custom-control-label"
                  for="id_use_default_shipping"
                  >Use default shipping address:
                  {{default_shipping_address.street_address|truncatechars:10}}</label
                >
              </div>
              {% endif %}
              <hr />
              <h3>Billing Address</h3>
              <div class="hideable-billing-form">
                <div class="md-form mb-5">
                  <input
                    type="text"
                    name="billing_address"
                    id="id_billing_address"
                    class="form-control"
                    placeholder="1234 Main St"
                  />
                  <label for="id_billing_address" class=""
                    >Address<span class="asteriskField">*</span></label
                  >
                </div>

                <!--address-2-->
                <div class="md-form mb-5">
                  <input
                    type="text"
                    name="billing_address2"
                    id="id_billing_address"
                    class="form-control"
                    placeholder="Apartment or suite"
                  />
                  <label for="id_billing_address" class=""
                    >Address 2 (optional)</label
                  >
                </div>

                <!--Grid row-->
                <div class="row">
                  <!--Grid column-->
                  <div class="col-lg-6 col-md-6 mb-4">
                    <label for="billing_country" class="">
                      Billing Country
                    </label>
                    {{form.billing_country}}
                  </div>
                  <!--Grid column-->
                  <!--Grid column-->
                  <div class="col-lg-6 col-md-6 mb-4">
                    <label for="id_billing_zip"
                      >Zip code<span class="asteriskField">*</span></label
                    >
                    <input
                      type="text"
                      name="billing_zip"
                      class="form-control"
                      id="id_billing_zip"
                      placeholder=""
                    />
                    <div class="invalid-feedback">Zip code required.</div>
                  </div>
                  <!--Grid column-->
                </div>
                <!--Grid row-->

                <hr />
                <div class="custom-control custom-checkbox">
                  <input
                    type="checkbox"
                    name="set_default_billing"
                    class="custom-control-input"
                    id="id_set_default_billing"
                  />
                  <label
                    class="custom-control-label"
                    for="id_set_default_billing"
                    >Save this billing address for future</label
                  >
                </div>
              </div>
              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input
                  type="checkbox"
                  name="use_default_billing"
                  class="custom-control-input"
                  id="id_use_default_billing"
                />
                <label class="custom-control-label" for="id_use_default_billing"
                  >Use default billing address:
                  {{default_billing_address.street_address|truncatechars:10}}</label
                >
              </div>
              {% endif %}
              <hr />
              <a role="button" class="btn btn-primary btn-lg btn-block" onclick="validateForm()">
                Continue to checkout
              </a>
            </form>
          </div>
          <!--/.Card-->
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-md-4 mb-4">{% include 'order-snippet.html' %}</div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->
</div>
{% endblock content %}
{% block extra_body %}
<script type="text/javascript">
  // Animations initialization
  new WOW().init();
</script>
{% endblock extra_body %}
{% block extra_scripts %}
<script>
function displayErrorToast(message) {
  iziToast.error({
    title: "Error",
    message: message,
  });
}

var hideable_shipping_form = $(".hideable-shipping-form");
var hideable_billing_form = $(".hideable-billing-form");

var same_billing_address = document.querySelector(
  "input[name=same_billing_address]"
);

if ("{{default_shipping_address}}") {
  var use_default_shipping = document.querySelector(
    "input[name=use_default_shipping]"
  );
  use_default_shipping.addEventListener("change", function () {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else {
      hideable_shipping_form.show();
    }
  });
}
if ("{{default_billing_address}}") {
  var use_default_billing = document.querySelector(
    "input[name=use_default_billing]"
  );
  use_default_billing.addEventListener("change", function () {
    if (this.checked) {
      hideable_billing_form.hide();
      same_billing_address.setAttribute("disabled", true);
    } else {
      hideable_billing_form.show();
      same_billing_address.removeAttribute("disabled");
    }
  });
}

same_billing_address.addEventListener("change", function () {
  if (this.checked) {
    hideable_billing_form.hide();
    use_default_billing.setAttribute("disabled", true);
  } else {
    hideable_billing_form.show();
    use_default_billing.removeAttribute("disabled");
  }
});

const validateBilling = () => {
  console.log("validateShipping");
  const billingAddress = document
    .getElementById("id_billing_address")
    .value.trim();
  if (billingAddress.length <= 0) {
    displayErrorToast("Billing address cannot be empty!");
     document
    .getElementById("id_billing_address").focus();
    return false;
  }
  const billingCountry = document.getElementById("id_billing_country").value;
  if (billingCountry.length <= 0) {
    displayErrorToast("Billing country is not selected!");
    document.getElementById("id_billing_country").focus();
    return false;
  }
  const zip = document.getElementById("id_billing_zip").value;
  if (!(/^[0-9]*$/.test(zip)) || zip.length != 6) {
    displayErrorToast("Zip should contain exactly 6 numeric characters");
    document.getElementById("id_billing_zip").focus();
    return false;
  }
  return true;
};

const validateShipping = () => {
  console.log("validateShipping");
  const shippingAddress = document
    .getElementById("id_shipping_address")
    .value.trim();
  if (shippingAddress.length <= 0) {
    displayErrorToast("Shipping address cannot be empty!");
    document
    .getElementById("id_shipping_address").focus();
    return false;
  }
  const shippingCountry = document.getElementById("id_shipping_country").value;
  if (shippingCountry.length <= 0) {
    displayErrorToast("Shipping country is not selected!");
    document.getElementById("id_shipping_country").focus();
    return false;
  }
  const zip = document.getElementById("id_shipping_zip").value;
  if (!(/^[0-9]*$/.test(zip)) || zip.length != 6) {
    displayErrorToast("Zip should contain exactly 6 numeric characters");
    document.getElementById("id_shipping_zip").focus();
    return false;
  }
  return true;
};

const validate = () => {
  let shipping = false;
  let billing = false;

  if ("{{default_shipping_address}}") {
    const useDefaultShipping = document.getElementById(
      "id_use_default_shipping"
    );
    if (useDefaultShipping.checked) {
      shipping = true;
    } else {
      shipping = validateShipping();
    }
  } else {
    shipping = validateShipping();
  }

  const sameBillingAddress = document.getElementById("id_same_billing_address");

  if (sameBillingAddress.checked) {
    billing = shipping;
    return (billing && shipping);
  }

  if ("{{default_billing_address}}") {
    const useDefaultBilling = document.getElementById("id_use_default_billing");
    if (useDefaultBilling.checked) {
      billing = true;
    } else {
      billing = validateBilling();
    }
  } else {
    billing = validateBilling();
  }
  return (billing && shipping);
};

function validateForm() {
  if (validate()) {
    document.querySelector("#checkout-form").submit();
  }
}
</script>
{% endblock extra_scripts %}

templates/head-css.html
{% load static %}
<!-- Font Awesome -->
<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
/>
<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<!-- Material Design Bootstrap -->
<link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
<!-- Your custom styles (optional) -->
<link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
<!-- iziToast configuration -->
<link rel="stylesheet" href="{% static 'css/iziToast.min.css' %}">

templates/home-page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Material Design Bootstrap</title>
    {% include 'head-css.html' %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>

  <body>
    <!-- Navbar -->
    {% include 'navbar.html' %}
    <!-- /.Navbar -->
    <!--Carousel Wrapper-->
    {% include 'carousel.html' %}
    <!--/.Carousel Wrapper-->
    <!--Main layout-->
    <main>
      <div class="container">
        <!--Navbar-->
        <nav
          class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
        >
          <!-- Navbar brand -->
          <span class="navbar-brand">Categories:</span>

          <!-- Collapse button -->
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#basicExampleNav"
            aria-controls="basicExampleNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Collapsible content -->
          <div class="collapse navbar-collapse" id="basicExampleNav">
            <!-- Links -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#"
                  >All
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Shirts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Sport wears</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Outwears</a>
              </li>
            </ul>
            <!-- Links -->

            <form class="form-inline">
              <div class="md-form my-0">
                <input
                  class="form-control mr-sm-2"
                  type="text"
                  placeholder="Search"
                  aria-label="Search"
                />
              </div>
            </form>
          </div>
          <!-- Collapsible content -->
        </nav>
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">
          <!--Grid row-->
          <div class="row wow fadeIn">
            <!--Grid column-->
            {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">
              <!--Card-->
              <div class="card">
                <!--Card image-->
                <div class="view overlay">
                  <img
                    src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg"
                    class="card-img-top"
                    alt=""
                  />
                  <a href="{{item.get_absolute_url}}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{item.get_category_display}}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{item.get_absolute_url}}" class="dark-grey-text"
                        >{{item.title}}
                        <span
                          class="badge badge-pill {{item.get_label_display}}-color"
                          >NEW</span
                        >
                      </a>
                    </strong>
                  </h5>
                  <h4 class="font-weight-bold blue-text">
                    {% if item.discount_price %}
                    <strong>${{item.discount_price}}</strong>
                    {% else %}
                    <strong>${{item.price}}</strong>
                    {% endif %}
                  </h4>
                </div>
                <!--Card content-->
              </div>
              <!--Card-->
            </div>
            {% endfor %}
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->
        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">
            <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true"><strong>&laquo;</strong></span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true"><strong>&raquo;</strong></span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
          </ul>
        </nav>
        {% endif %}
        <!--Pagination-->
      </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    {% include 'footer.html' %}
    <!--/.Footer-->
    {% include 'bottom-scripts.html' %}
    <!-- Initializations -->
    <script type="text/javascript">
      // Animations initialization
      new WOW().init();
    </script>
  </body>
</html>

templates/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == "info" %}
<script>
  iziToast.info({
      title: "Info",
      message: "{{message}}",
      timeOut: 2500
  });
</script>
{% elif message.tags == "error" %}
<script>
  iziToast.error({
    title: "Oops",
    message: "{{message}}",
    timeOut: 2500
  });
</script>
{% elif message.tags == "warning" %}
<script>
  iziToast.warning({
    title: "Warning",
    message: "{{message}}",
    timeOut: 2500
  });
</script>
{% elif message.tags == "success" %}
<script>
  iziToast.success({
    title: "success",
    message: "{{message}}",
    timeOut: 2500
  });
</script>
{% endif %}
{% endfor %}
{% endif %}

templates/order-snippet.html
<!-- Heading -->
<h4 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted">Your cart</span>
  <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
</h4>
<!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
  {% for order_item in order.items.all %}
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
    </div>
    <span class="text-muted">Rs.{{order_item.get_final_price}}</span>
  </li>
  {% endfor %}
  <li class="list-group-item d-flex justify-content-between">
    <span>Total (USD)</span>
    <strong>Rs.{{order.get_total}}</strong>
  </li>
  {% if order.coupon %}
  <li class="list-group-item d-flex justify-content-between bg-light">
    <div class="text-success">
      <h6 class="my-0">Promo code</h6>
      <small>{{order.coupon.code}}</small>
    </div>
    <span class="text-success">-Rs.{{order.get_coupon_discount}}</span>
  </li>
  <li class="list-group-item d-flex justify-content-between">
    <span>Discounted Total (USD)</span>
    <strong
      ><del>Rs.{{order.get_total}}</del> Rs.{{order.get_total_after_coupon}}</strong
    >
  </li>
  {% endif %}
</ul>
<!-- Cart -->
{% if show_coupon_form %}
<!-- Promo code -->
<form class="card p-2" action="{% url 'add-coupon' %}" method="POST">
  {% csrf_token %}
  <div class="input-group">
    <select
      name="code"
      class="custom-select"
      placeholder="Promo Code"
      aria-label="Recipient&#39;s username"
      aria-describedby="basic-addon2"
      required
      id="id_code"
    >
      <option value="">SELECT</option>
      <option value="FIRST_TIME">FIRST_TIME</option>
      <option value="THREE_THOUSAND">THREE_THOUSAND</option>
    </select>
    <div class="input-group-append">
      <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">
        Redeem
      </button>
    </div>
  </div>
</form>
<!-- Promo code -->
{% endif %}